config/routes.rb
Rails.application.routes.draw do
  get 'requests/code'
  
  resources :pages
  resources :accounts
  resources :configs

  root 'hello#index'
  get 'dashboard/index'
  post 'login/create'
  delete 'login/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
	validates :ip, uniqueness: true
	belongs_to :user

	enum status: [:on, :off]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/backup.rb
class Backup < ApplicationRecord
  enum coin: [:bitcoin, :dogecoin, :litecoin, :blackcoin, :bitcore, :dashcoin, :primecoin, :peercoin, :other]
  enum status: [:not_code, :on, :off, :test]
end

app/models/config.rb
class Config < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :group, optional: true

  enum coin: [:bitcoin, :dogecoin, :litecoin, :blackcoin,
              :bitcore, :dashcoin, :primecoin, :peercoin, :ethereum, :bitcoincash, :potcoin, :kb3coin,  :other]
  enum status: [:on, :off]
  enum chuoi: [:yes, :no]
end

app/models/slot.rb
class Slot < ApplicationRecord
end

app/models/standard.rb
class Standard < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_token
  enum role: [:admin, :editor, :member]
	validates :username, uniqueness: true
	has_many :accounts
end

app/controllers/configs_controller.rb
class ConfigsController < ApplicationController
  def index
    @configs = Config.all
  end

  def new
    redirect_to configs_path unless is_admin?
    @config = Config.new
  end

  def update
    Config.update config_params
    redirect_to configs_path
  end

  def edit
    redirect_to configs_path unless is_admin?
    @config = Config.find_by id: params[:id]
  end

  def create
    Config.create config_params
    redirect_to configs_path
  end

  def destroy
    redirect_to configs_path unless is_admin?
    config = Config.find_by id: params[:id]
    config.delete
    redirect_to configs_path
  end

  private
  def config_params
    params.require(:config).permit :id, :key, :value
  end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def index
  end

  def login_facebook
  end

  def do_login_facebook
  	@cookie = params[:cookie]
  end

  def anticaptcha
		@apikey = info_params[:apikey]
		@sitekey = info_params[:sitekey]
		@location = info_params[:location]
  end

  def cheapcaptcha
  end

  def banner
  end

  private
  def info_params
    params.permit :apikey, :sitekey, :location
  end
end

app/controllers/lvc_controller.rb
class LvcController < ApplicationController
  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login?
    session[:username]
  end
end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/lvc_helper.rb
module LvcHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/configs/edit.html.erb
<div id="page-content-wrapper">
  <div class="container-fluid">
    <%= form_for @config, class: 'form-group' do |f| %>
        <label>name</label>
        <%= f.text_field :key %><br>
        <label>value</label>
        <%= f.text_area :value, rows: 15, cols: 100 %><br>
        <%= f.submit :OK %>
    <% end %>
  </div>
</div>

app/views/configs/index.html.erb
<div id="page-content-wrapper">
  <div class="container-fluid">
    <a class="btn btn-primary" href="<%= new_config_path %>">New config</a>
  </div>
    <table class="table">
      <thead>
      <th>key</th>
      <th>value</th>
      <th>action</th>
      </thead>
      <tbody>
      <% @configs.each do |p| %>
          <tr>
            <td><%= p.id %></td>
            <td><%= p.value %></td>
            <td><a href="<%= edit_config_path(p) %>">Edit</a>
                <%= link_to 'Destroy', config_path(p),
                    data: {:confirm => 'Are you sure?'}, :method => :delete %></td>
            </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/configs/new.html.erb
<div id="page-content-wrapper">
  <div class="container-fluid">
    <%= form_for @config, class: 'form-group' do |f| %>
        <label>name</label>
        <%= f.text_field :key %><br>
        <label>value</label>
        <%= f.text_area :value, rows: 15, cols: 100 %><br>
        <%= f.submit :OK %>
    <% end %>
  </div>
</div>