config/routes.rb
Rails.application.routes.draw do
  get 'requests/code'
  
  resources :pages
  resources :accounts
  resources :configs

  root 'hello#index'
  get 'dashboard/index'
  post 'login/create'
  delete 'login/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
	validates :ip, uniqueness: true
	belongs_to :user

	enum status: [:on, :off]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/backup.rb
class Backup < ApplicationRecord
  enum coin: [:bitcoin, :dogecoin, :litecoin, :blackcoin, :bitcore, :dashcoin, :primecoin, :peercoin, :other]
  enum status: [:not_code, :on, :off, :test]
end

app/models/config.rb
class Config < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :group, optional: true

  enum coin: [:bitcoin, :dogecoin, :litecoin, :blackcoin,
              :bitcore, :dashcoin, :primecoin, :peercoin, :ethereum, :bitcoincash, :potcoin, :kb3coin,  :other]
  enum status: [:on, :off]
  enum chuoi: [:yes, :no]
end

app/models/slot.rb
class Slot < ApplicationRecord
end

app/models/standard.rb
class Standard < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_token
  enum role: [:admin, :editor, :member]
	validates :username, uniqueness: true
	has_many :accounts
end

app/controllers/backups_controller.rb
class BackupsController < ApplicationController
  def index
    if params[:search]
      @value = params[:value]
      @backups = Backup.where("name like '%#{params[:value]}%'").order :id
    else
      @backups = Backup.all.order :id
    end
  end

  def new
    @backup = Backup.new
  end

  def create
    Backup.create backup_params
    redirect_to backups_path
  end

  def edit
    @backup = Backup.find_by id: params[:id]
    redirect_to backups_path and return unless (is_admin? || @backup.not_code?)
  end

  def update
    backup = Backup.find_by id: params[:id]
    redirect_to backups_path and return unless (is_admin? || backup.not_code?)
    backup.update backup_params
    redirect_to backups_path
  end

  def destroy
    backup = Backup.find_by id: params[:id]
    redirect_to backups_path and return unless (is_admin? || backup.not_code?)
    backup.delete
    redirect_to backups_path
  end

  private
  def backup_params
    p = if is_admin?
      params.require(:backup).permit :id, :name, :description, :coin, :content, :time, :status
    else
      params.require(:backup).permit :id, :name, :description, :coin, :time, :content
    end
    p[:status] = :not_code unless p[:status]
    p
  end

  def redirect_if_no_admin
    redirect_to(backups_path) and return unless is_admin?
  end
end

app/controllers/lvc_controller.rb
class LvcController < ApplicationController
  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login?
    session[:username]
  end
end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/lvc_helper.rb
module LvcHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/backups/edit.html.erb
<div id="page-content-wrapper">
  <div class="container-fluid col-md-8">
    <%= form_for @backup, class: 'form-group' do |f| %>
        <label>name</label>
        <%= f.text_field :name, class: 'form-control' %><br>
        <label>Type</label>
        <%= f.select :coin, Page.coins.collect {|k, v| [k, k]}, class: 'form-control' %><br>
        <label>Status</label>
        <%= f.select :status, Page.statuses.collect {|k, v| [k, k]}, class: 'form-control' %><br>
        <label>time</label>
        <%= f.number_field :time, class: 'form-control' %><br>
        <label>description</label>
        <%= f.text_field :description, class: 'form-control' %><br>
        <label>content</label>
        <%= f.text_area :content, class: 'form-control', col: 150, rows: 15 %><br>
        <%= f.submit :OK, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/backups/index.html.erb
<div id="page-content-wrapper">
  <div class="container-fluid">
    <div>
      <a class="btn btn-primary" href="<%= new_backup_path %>">New Backup</a>
      <form method="get" action="<%= pages_path %>">
        <input name="search" value="1" hidden><br>
        <input name="value" value="<%= @value %>">
        <button class="btn btn-primary">Ok</button>
      </form>
    </div>
    <table class="table">
      <thead>
        <th>Id</th>
        <th>Name</th>
        <th>Coin</th>
        <th>Status</th>
        <th>Time</th>
        <th>Description</th>
        <th>Action</th>
      </thead>
      <tbody>
        <% @backups.each do |p| %>
          <tr>
            <td><%= p.id %></td>
            <td><%= p.name %></td>
            <td><label class="label label-info"><%= p.coin %></label></td>
            <%
               color = p.not_code? ? 'label label-warning' : (p.on? ? 'label label-success' : 'label label-danger')
            %>
            <td><label class="<%= color %>"><%= p.status %></label></td>
            <td><%= p.time %></td>
            <td><%= p.description %></td>
            <td><a class="label label-primary" href="<%= edit_backup_path(p) %>">Edit</a>
              <%= link_to 'Destroy', backup_path(p), class: "label label-danger",
                          data: {:confirm => 'Are you sure?'}, :method => :delete %></td>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/backups/new.html.erb
<div id="page-content-wrapper">
  <div class="container-fluid col-md-8">
    <%= form_for @backup, class: 'form-group' do |f| %>
        <label>name</label>
        <%= f.text_field :name, class: 'form-control' %><br>
        <label>Type</label>
        <%= f.select :coin, Page.coins.collect {|k, v| [k, k]}, class: 'form-control' %><br>
        <label>Status</label>
        <%= f.select :status, Page.statuses.collect {|k, v| [k, k]}, value: 'not_code', class: 'form-control' %><br>
        <label>time</label>
        <%= f.number_field :time, class: 'form-control' %><br>
        <label>description</label>
        <%= f.text_field :description, class: 'form-control' %><br>
        <label>content</label>
        <%= f.text_area :content, class: 'form-control', col: 150, rows: 15 %><br>
        <%= f.submit :OK, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>