config/routes.rb
Rails.application.routes.draw do
  get 'requests/code'
  
  resources :pages
  resources :accounts
  resources :configs

  root 'hello#index'
  get 'dashboard/index'
  post 'login/create'
  delete 'login/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
	validates :ip, uniqueness: true
	belongs_to :user

	enum status: [:on, :off]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/backup.rb
class Backup < ApplicationRecord
  enum coin: [:bitcoin, :dogecoin, :litecoin, :blackcoin, :bitcore, :dashcoin, :primecoin, :peercoin, :other]
  enum status: [:not_code, :on, :off, :test]
end

app/models/config.rb
class Config < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :group, optional: true

  enum coin: [:bitcoin, :dogecoin, :litecoin, :blackcoin,
              :bitcore, :dashcoin, :primecoin, :peercoin, :ethereum, :bitcoincash, :potcoin, :kb3coin,  :other]
  enum status: [:on, :off]
  enum chuoi: [:yes, :no]
end

app/models/slot.rb
class Slot < ApplicationRecord
end

app/models/standard.rb
class Standard < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_token
  enum role: [:admin, :editor, :member]
	validates :username, uniqueness: true
	has_many :accounts
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @accounts = Account.where(user_id: session['user_id']);
  end

  def new
    @account = Account.new
  end

  def create
    Account.create account_params.merge({user_id: session['user_id']})
    redirect_to accounts_path
  end

  def edit
    @account = Account.find_by id: params[:id]
  end

  def update
    account = Account.find_by id: params[:id]
    account.update account_params
    redirect_to accounts_path
  end

  def destroy
    account = Account.find_by id: params[:id]
    account.delete
    redirect_to accounts_path
  end

  private
  def account_params
    params.require(:account).permit :id, :ip, :email, :username, :password, :api_key, :bitcoin, :dogecoin, :list
  end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def index
  end

  def login_facebook
  end

  def do_login_facebook
  	@cookie = params[:cookie]
  end

  def anticaptcha
		@apikey = info_params[:apikey]
		@sitekey = info_params[:sitekey]
		@location = info_params[:location]
  end

  def cheapcaptcha
  end

  def banner
  end

  private
  def info_params
    params.permit :apikey, :sitekey, :location
  end
end

app/controllers/lvc_controller.rb
class LvcController < ApplicationController
  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login?
    session[:username]
  end
end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/lvc_helper.rb
module LvcHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/accounts/edit.html.erb
<div id="page-content-wrapper">
  <div class="container-fluid">
    <%= form_for @account, class: 'form-group' do |f| %>
        <label>ip</label>
        <%= f.text_field :ip %><br>
        <label>email</label>
        <%= f.text_field :email %><br>
        <label>username</label>
        <%= f.text_field :username %><br>
        <label>password</label>
        <%= f.text_field :password %><br>
        <label>api_key</label>
        <%= f.text_field :api_key %><br>
        <label>bitcoin</label>
        <%= f.text_field :bitcoin %><br>
        <label>dogecoin</label>
        <%= f.text_field :dogecoin %><br>
        <label>list</label>
        <%= f.text_field :list %><br>
        <%= f.submit :OK %>
    <% end %>
  </div>
</div>

app/views/accounts/index.html.erb
<div id="page-content-wrapper">
  <div class="container-fluid">
  <div>
    <a class="btn btn-primary" href="<%= new_account_path %>" >Add new</a>
  </div>
    <table class="table">
      <thead>
      <th>Ip</th>
      <th>Email</th>
      <th>username</th>
      <th>password</th>
      <th>apikey</th>
      <th>bitcoin</th>
      <th>dogecoin</th>
      <th>list</th>
      <th>action</th>
      </thead>
      <tbody>
      <% @accounts.each do |a| %>
          <tr>
            <td><%= a.ip %></td>
            <td><%= a.email %></td>
            <td><%= a.username %></td>
            <td><%= a.api_key %></td>
            <td><%= a.password %></td>
            <td><%= a.bitcoin %></td>
            <td><%= a.dogecoin %></td>
            <td><%= a.list %></td>
            <td>
              <a href="<%= edit_account_path(a) %>">Edit</a>
              <%= link_to 'Destroy', account_path(a),
                          data: {:confirm => 'Are you sure?'}, :method => :delete %></td>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/accounts/new.html.erb
<div id="page-content-wrapper">
  <div class="container-fluid">
    <%= form_for @account, class: 'form-group' do |f| %>
        <label>ip</label>
        <%= f.text_field :ip %><br>
        <label>email</label>
        <%= f.text_field :email %><br>
        <label>username</label>
        <%= f.text_field :username %><br>
        <label>password</label>
        <%= f.text_field :password %><br>
        <label>api_key</label>
        <%= f.text_field :api_key %><br>
        <label>bitcoin</label>
        <%= f.text_field :bitcoin %><br>
        <label>dogecoin</label>
        <%= f.text_field :dogecoin %><br>
        <label>list</label>
        <%= f.text_field :list %><br>
        <%= f.submit :OK %>
    <% end %>
  </div>
</div>